title: William Lumme
description: "Aficionado of Software Engineering, Data, and DevOps."
baseurl: "/personal_website"
url: ""
source_url: "https://github.com/Willlumm/personal_website"

remote_theme: willlumm/swiss
theme_color: asparagus

homepage_image: assets/william_lumme.png
homepage_image_alt: "Photo of William"

socials:
  - link: github
    username: willlumm
  - link: linkedin
    username: william-lumme

plugins:
  - jekyll-feed
