title: William Lumme
description: I engineer data solutions.
baseurl: ""
url: ""
source_url: "https://github.com/Willlumm/personal_website"

remote_theme: willlumm/swiss
theme_color: asparagus

homepage_image: homepage_small.png
homepage_image_alt: "Photo of William"

socials:
  - link: github
    username: willlumm
  - link: linkedin
    username: william-lumme

plugins:
  - jekyll-feed
